/* Generated by scripts/generate_website_runtime_config.py — do not edit */
window.STEADY_RUNTIME = {
  "repo": "LabRatKali/steady-sync",
  "tokenObfHex": "0619044606163a11050d71505f27343e5c2b7b2f0118463d681f2d015955366d083153225e03546230070624487a1a373f2850314b122f06462d071e173b4b20323a1f271b102309327e2f3f57265a263d6a350728180241323212020c",
  "googleClientId": "REPLACE_WITH_GOOGLE_OAUTH_WEB_CLIENT_ID.apps.googleusercontent.com",
  "mailer": {
    "provider": "",
    "apiKeyObfHex": "",
    "fromEmail": "",
    "magicLinkBase": "https://labratkali.github.io/steady-web/dashboard.html",
    "replyTo": ""
  }
};
