/* Generated by scripts/generate_website_runtime_config.py — do not edit */
window.STEADY_RUNTIME = {
  "repo": "LabRatKali/steady-sync",
  "tokenObfHex": "0619044606163a11050d71505f27343e5c2b7b2f0118463d681f2d015955366d083153225e03546230070624487a1a373f2850314b122f06462d071e173b4b20323a1f271b102309327e2f3f57265a263d6a350728180241323212020c",
  "googleClientId": "1016955147858-s0fl8bvl5f20705doj7qhpio3211jadq.apps.googleusercontent.com",
  "monetizeProvider": "adsterra",
  "monetizeAppId": "",
  "monetizeScriptUrl": "",
  "monetagScriptUrl": "",
  "monetagZoneId": "",
  "adsbitvexScriptUrl": "",
  "rewardScriptUrl": "",
  "monetizeRewardWebUrl": "",
  "monetizeBannerHtml": "<script>\n  atOptions = {\n    'key' : 'd737196962ef25449dcb66c5655248f1',\n    'format' : 'iframe',\n    'height' : 250,\n    'width' : 300,\n    'params' : {}\n  };\n</script>\n<script src=\"https://www.highperformanceformat.com/d737196962ef25449dcb66c5655248f1/invoke.js\"></script>\n<script async=\"async\" data-cfasync=\"false\" src=\"https://pl30566397.effectivecpmnetwork.com/aa9f63337d56fa208fd27e208e22774a/invoke.js\"></script>\n<div id=\"container-aa9f63337d56fa208fd27e208e22774a\"></div>",
  "websiteBannerHtml": "<script>\n  atOptions = {\n    'key' : 'd737196962ef25449dcb66c5655248f1',\n    'format' : 'iframe',\n    'height' : 250,\n    'width' : 300,\n    'params' : {}\n  };\n</script>\n<script src=\"https://www.highperformanceformat.com/d737196962ef25449dcb66c5655248f1/invoke.js\"></script>\n<script async=\"async\" data-cfasync=\"false\" src=\"https://pl30566397.effectivecpmnetwork.com/aa9f63337d56fa208fd27e208e22774a/invoke.js\"></script>\n<div id=\"container-aa9f63337d56fa208fd27e208e22774a\"></div>",
  "monetizeRewardHtml": "<script>\n  atOptions = {\n    'key' : 'd737196962ef25449dcb66c5655248f1',\n    'format' : 'iframe',\n    'height' : 250,\n    'width' : 300,\n    'params' : {}\n  };\n</script>\n<script src=\"https://www.highperformanceformat.com/d737196962ef25449dcb66c5655248f1/invoke.js\"></script>\n<script src=\"https://pl30566396.effectivecpmnetwork.com/75/7d/b0/757db01b5a07eb68043c6fd140726fed.js\"></script>",
  "monetizeMinWatchSeconds": 12,
  "monetizeAllowDemo": false,
  "mailer": {
    "provider": "resend",
    "apiKeyObfHex": "",
    "fromEmail": "Steady <onboarding@resend.dev>",
    "magicLinkBase": "https://steady.less-phone.workers.dev/dashboard.html",
    "proxyUrl": "https://steady.less-phone.workers.dev/api/mail",
    "replyTo": ""
  }
};
